import './index.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function Layout({ children }) {
  return (
    <html lang="en">
      <body className='h-screen w-screen p-0 m-0'>
        <>
      
          {children}
        </>
        </body>
    </html>
  )
}
