import './index.css';

export const metadata = {
  title:{
    default:"NextJs Practise", //fallback if not title is present in the child
    template:"%s | TemplateWrapper" , // if the title is present will put the title from child in %s place
    // absolute:""  if we want to break from the tempalate title format just put absolute in the child's title object 
  },
  description: 'Generated by Next.js',
}

export default function Layout({ children }) {
  return (
    <html lang="en">
      <body className='h-screen w-screen p-0 m-0'>
        <>
      
          {children}
        </>
        </body>
    </html>
  )
}
